/*==============================================================*/
/* BORRAR SECUENCIAS                                            */
/*==============================================================*/
DROP SEQUENCE SEQ_OPE_ID;
DROP SEQUENCE SEQ_TIES_ID;
DROP SEQUENCE SEQ_TRON_ID;
DROP SEQUENCE SEQ_EST_ID;
DROP SEQUENCE SEQ_VAG_ID;
DROP SEQUENCE SEQ_RUT_ID;
DROP SEQUENCE SEQ_RUTEST_ID;
DROP SEQUENCE SEQ_HOR_ID;
DROP SEQUENCE SEQ_RUTHOR_ID;
DROP SEQUENCE SEQ_RUTALIM_ID;
DROP SEQUENCE SEQ_TIPA_ID;
DROP SEQUENCE SEQ_PAR_ID;
DROP SEQUENCE SEQ_PARRUTALIM_ID;
DROP SEQUENCE SEQ_PARHOR_ID;

/*==============================================================*/
/* BORRAR INFORMACION TABLAS                                    */
/*==============================================================*/
DELETE FROM PARA_HORA;
DELETE FROM RUTA_HORA;
DELETE FROM RUTA_ESTA;
DELETE FROM TIPO_PARADERO;
DELETE FROM OPERADOR;
DELETE FROM TIPO_ESTACION;
DELETE FROM TRONCAL;
DELETE FROM VAGON;
DELETE FROM RUTA;
DELETE FROM HORARIO;
DELETE FROM PAR_RUT_ALIM;
DELETE FROM PARADERO;
DELETE FROM RUTA_ALIMEN;
DELETE FROM ESTACION;

/*==============================================================*/
/* BORRAR TABLAS                                                */
/*==============================================================*/
DROP TABLE PARA_HORA CASCADE CONSTRAINTS;
DROP TABLE RUTA_HORA CASCADE CONSTRAINTS;
DROP TABLE RUTA_ESTA CASCADE CONSTRAINTS;
DROP TABLE TIPO_PARADERO CASCADE CONSTRAINTS;
DROP TABLE OPERADOR CASCADE CONSTRAINTS;
DROP TABLE TIPO_ESTACION CASCADE CONSTRAINTS;
DROP TABLE TRONCAL CASCADE CONSTRAINTS;
DROP TABLE VAGON CASCADE CONSTRAINTS;
DROP TABLE RUTA CASCADE CONSTRAINTS;
DROP TABLE HORARIO CASCADE CONSTRAINTS;
DROP TABLE PAR_RUT_ALIM CASCADE CONSTRAINTS;
DROP TABLE PARADERO CASCADE CONSTRAINTS;
DROP TABLE RUTA_ALIMEN CASCADE CONSTRAINTS;
DROP TABLE ESTACION CASCADE CONSTRAINTS;

/*==============================================================*/
/* BORRAR USUARIO                                               */
/*==============================================================*/
/*DROP USER TRANSMI CASCADE;*/
