/*==============================================================*/
/* OPERADOR                                                     */
/*==============================================================*/
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'CIUDAD MÓVIL', '679-59-00', ' Calle 183 No. 51 – 65', 'Gustavo Gómez Bernal', 'http://www.ciudadmovil.com.co/');
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'CONNEXIÓN MÓVIL', '779-93-00', 'Av. Calle 57r # sur No. 72f - 50', 'Santiago Cucalón', NULL);
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'METROBUS', '769-77-44', 'Calle 48 Sur No. 23-35','Raúl Enrique Segura', 'http://www.metrobus.com.co/');
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'TRANSMASIVO', '275-10-15', 'direc', 'Mario Rodríguez', NULL);
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'EXPRESS DEL FUTURO', '291-44-00', 'Calle 80 No. 96 – 91', 'Orlando Vanegas Silva', 'http://www.expressdelfuturo.co/');
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'SI 99 S.A.', '770-90-60', 'Calle 63Sur Avenida Caracas', 'Víctor Raúl Martínez', NULL);
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'SOMOS K', '453-30-68', 'Carrera 86 Bis No. 45-57 Sur', 'Enrique Wolff Marulanda', 'http://www.somos.co/');
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'CONSORCIO EXPRESS', '742-47-11', 'Calle 32sur No. 3C-08', 'Camilo Alfonso Sabogal', NULL);
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'GMOVIL S.A.S.', '384-88-00', 'Calle 24d No. 86-53', 'Juan Fernando Cajiao', 'http://www.gmovilsas.com.co/');
INSERT INTO OPERADOR (ID_OPERADOR, NOMBRE, TELEFONO, DIRECCION, REPRESENTANTE, PAGINA_WEB) VALUES (SEQ_OPE_ID.NEXTVAL, 'TRANZIT S.A.S.', '7455700', ' Calle 6 Sur No.15A-24 Piso 4', 'Edna Piedad Cubillos', NULL);
           

/*==============================================================*/
/* TIPO_ESTACION                                                */
/*==============================================================*/
INSERT INTO TIPO_ESTACION (ID_TIPO_ESTA, NOMBRE) VALUES (SEQ_TIES_ID.NEXTVAL, 'Portal');
INSERT INTO TIPO_ESTACION (ID_TIPO_ESTA, NOMBRE) VALUES (SEQ_TIES_ID.NEXTVAL, 'De transferencia');
INSERT INTO TIPO_ESTACION (ID_TIPO_ESTA, NOMBRE) VALUES (SEQ_TIES_ID.NEXTVAL, 'Intermedias');
INSERT INTO TIPO_ESTACION (ID_TIPO_ESTA, NOMBRE) VALUES (SEQ_TIES_ID.NEXTVAL, 'Sencillas');
INSERT INTO TIPO_ESTACION (ID_TIPO_ESTA, NOMBRE) VALUES (SEQ_TIES_ID.NEXTVAL, 'Sin intercambio');

/*==============================================================*/
/* TRONCAL                                                      */
/*==============================================================*/
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'Avenida Caracas', 'A', 'Azul Oscuro','Caracas', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='SI 99 S.A.'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'Autopista Norte', 'B', 'Verde','Norte', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='CIUDAD MÓVIL'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'Avenida Suba', 'C', 'Amarillo','Suba', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='TRANSMASIVO'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'CL 80', 'D', 'Morado','CALLE 80', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='EXPRESS DEL FUTURO'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'NQS Central', 'E', 'Cafe','NQS Central', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='SOMOS K'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'Americas', 'F', 'Rojo','Americas', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='METROBUS'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'NQS Sur', 'G', 'Azul Claro','NQS Sur', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='CONNEXIÓN MÓVIL'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'Avenida Ciudad Villa', 'H', 'Naranja','Caracas Sur', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='CONSORCIO EXPRESS'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'Eje Ambiental', 'J', 'Rosado','Eje Ambiental', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='GMOVIL S.A.S.'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'Avenida el Dorado', 'K', 'Piel','Calle 26', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='CIUDAD MÓVIL'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'KR 10', 'L', 'Aguamarina','Carrera 10', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='TRANZIT S.A.S.'));
INSERT INTO TRONCAL (ID_TRONCAL, NOMBRE_VIA, ZONA, COLOR_ZONA, NOMBRE_ZONA, ID_OPERADOR) VALUES (SEQ_TRON_ID.NEXTVAL, 'KR 7', 'M', 'Violeta','Carrera 7', (SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='EXPRESS DEL FUTURO'));

/*==============================================================*/
/* ESTACION                                                     */
/*==============================================================*/
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Portal de la 80','Calle 80 con Avenida Occidente','Engativá','4,71','-74,1106',1,0,1,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'), (SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Portal'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Quirigua','AC 80 - KR 94','Engativá', NULL,NULL,0,0,2,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Intermedias'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Carrera 90','AC 80 - KR 90','Engativá', NULL,NULL,0,0,3,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Intermedias'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Av. Cali','Calle 80 con Av Cali','Engativá', NULL,NULL,0,0,4,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='De transferencia'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Granja - Carrera 77','Carrera 77','Engativá', NULL,NULL,0,0,5,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Sencillas'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Minuto de Dios','Calle 80 con Carrera 73A','Engativá', NULL,NULL,0,0,6,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Sencillas'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Boyacá','Calle 80 con Av. Carrera 71','Engativá', NULL,NULL,0,0,7,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='De transferencia'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Ferias','Av.Calle 80 con Transversal 69R','Engativá', NULL,NULL,0,0,8,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Intermedias'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Avenida 68','Av.Calle 80 con Carrera 68C','Engativá', NULL,NULL,0,0,9,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Sencillas'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Carrera 53','Av.Calle 80 con Carrera 65','Barrios Unidos', NULL,NULL,0,0,10,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='De transferencia'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Carrera 47','Av.Calle 80 con Carrera 58','Barrios Unidos', NULL,NULL,0,0,11,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Sin intercambio'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Escuela Militar','Av.Calle 80 con Av.Carrera 50','Barrios Unidos', NULL,NULL,0,0,12,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Intermedias'));
INSERT INTO ESTACION (ID_ESTACION, NOMBRE, DIRECCION, LOCALIDAD, LATITUD, LONGITUD, ESTA_INCIAL, ESTA_FINAL, ORDEN, ID_TRONCAL, ID_TIPO_ESTA) VALUES (SEQ_EST_ID.NEXTVAL, 'Polo','Av.Calle 80 con Carrera 27','Barrios Unidos', NULL,NULL,0,1,13,(SELECT ID_TRONCAL FROM TRONCAL WHERE ZONA='D'),(SELECT ID_TIPO_ESTA FROM TIPO_ESTACION WHERE NOMBRE='Sin intercambio'));

/*==============================================================*/
/* VAGON                                                        */
/*==============================================================*/
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 2', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 3', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Quirigua'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 90'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Ferias'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Escuela Militar'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Minuto de Dios'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 2', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Minuto de Dios'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 53'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 2', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 53'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Av. Cali'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 2', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Av. Cali'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 47'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 2', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 47'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 3', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 47'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Polo'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 2', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Polo'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 3', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Polo'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Granja - Carrera 77'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Boyacá'));
INSERT INTO VAGON (ID_VAGON, NOMBRE, ID_ESTACION) VALUES (SEQ_VAG_ID.NEXTVAL, 'Vagon 1', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Avenida 68'));


/*==============================================================*/
/* RUTA                                                         */
/*==============================================================*/
INSERT INTO RUTA(ID_RUTA, NOMBRE, SENTIDO) VALUES (SEQ_RUT_ID.NEXTVAL, 'B10', 'N');
INSERT INTO RUTA(ID_RUTA, NOMBRE, SENTIDO) VALUES (SEQ_RUT_ID.NEXTVAL, 'C15', 'S');
INSERT INTO RUTA(ID_RUTA, NOMBRE, SENTIDO) VALUES (SEQ_RUT_ID.NEXTVAL, 'A8', 'O');
INSERT INTO RUTA(ID_RUTA, NOMBRE, SENTIDO) VALUES (SEQ_RUT_ID.NEXTVAL, 'A90', 'E');
INSERT INTO RUTA(ID_RUTA, NOMBRE, SENTIDO) VALUES (SEQ_RUT_ID.NEXTVAL, 'F14', 'NO');
INSERT INTO RUTA(ID_RUTA, NOMBRE, SENTIDO) VALUES (SEQ_RUT_ID.NEXTVAL, 'F10', 'NE');
INSERT INTO RUTA(ID_RUTA, NOMBRE, SENTIDO) VALUES (SEQ_RUT_ID.NEXTVAL, 'C45', 'SO');
INSERT INTO RUTA(ID_RUTA, NOMBRE, SENTIDO) VALUES (SEQ_RUT_ID.NEXTVAL, 'B27', 'SE');


/*==============================================================*/
/* RUTA_ESTA                                                    */
/*==============================================================*/
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 1, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 1' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Avenida 68')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='C15'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 2, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 1' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Polo')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='B10'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 2, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 2' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Polo')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='B10'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 2, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 3' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Polo')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='B10'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 3, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 1' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Escuela Militar')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F14'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 4, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 2' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Av. Cali')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F14'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 5, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 1' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Minuto de Dios')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F14'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 6, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 1' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 53')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F14'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 6, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 2' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 53')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F14'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 7, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 2' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 47')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F14'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 7, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 3' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Carrera 47')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F14'));
INSERT INTO RUTA_ESTA(ID_RUTA_ESTA, ORDEN, ID_VAGON, ID_RUTA) VALUES (SEQ_RUTEST_ID.NEXTVAL, 8, (SELECT ID_VAGON FROM VAGON WHERE NOMBRE='Vagon 1' AND ID_ESTACION=(SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Granja - Carrera 77')), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F14'));

/*==============================================================*/
/* HORARIO                                                      */
/*==============================================================*/
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'E', TO_DATE('01/01/1990 04:00', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 21:00', 'dd/MM/YYYY HH24:MI'));
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'E', TO_DATE('01/01/1990 04:30', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 22:30', 'dd/MM/YYYY HH24:MI'));
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'D', TO_DATE('01/01/1990 08:00', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 11:00', 'dd/MM/YYYY HH24:MI'));
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'S', TO_DATE('01/01/1990 06:00', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 16:00', 'dd/MM/YYYY HH24:MI'));
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'S', TO_DATE('01/01/1990 10:00', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 14:00', 'dd/MM/YYYY HH24:MI'));
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'D', TO_DATE('01/01/1990 03:00', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 13:00', 'dd/MM/YYYY HH24:MI'));
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'E', TO_DATE('01/01/1990 05:00', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 10:00', 'dd/MM/YYYY HH24:MI'));
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'D', TO_DATE('01/01/1990 07:00', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 23:30', 'dd/MM/YYYY HH24:MI'));
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'E', TO_DATE('01/01/1990 09:00', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 12:00', 'dd/MM/YYYY HH24:MI'));
INSERT INTO HORARIO(ID_HORARIO, RANGO, HORA_COMIENZO, HORA_FIN) VALUES (SEQ_HOR_ID.NEXTVAL, 'S', TO_DATE('01/01/1990 11:00', 'dd/MM/YYYY HH24:MI'), TO_DATE('01/01/1990 14:30', 'dd/MM/YYYY HH24:MI'));

/*==============================================================*/
/* RUTA_HORA                                                    */
/*==============================================================*/
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='E' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='04:00'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='B10'));
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='E' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='09:00'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='C15'));
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='S' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='06:00'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='A90'));
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='E' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='05:00'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='A8'));
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='D' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='08:00'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='C45'));
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='S' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='10:00'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F10'));
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='D' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='03:00'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='B10'));
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='D' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='07:00'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='F14'));
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='S' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='11:00'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='C15'));
INSERT INTO RUTA_HORA(ID_RUTA_HORA, ID_HORARIO, ID_RUTA) VALUES (SEQ_RUTHOR_ID.NEXTVAL, (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='E' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='04:30'), (SELECT ID_RUTA FROM RUTA WHERE NOMBRE='B27'));

/*==============================================================*/
/* RUTA_ALIMEN                                                  */
/*==============================================================*/
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-1', 'Álamos', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='GMOVIL S.A.S.'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-2', 'Garcés Navas', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='SI 99 S.A.'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-3', 'Villas de Granada', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='TRANSMASIVO'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-4', 'Cortijo', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='SOMOS K'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-5', 'Colsubsidio', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='GMOVIL S.A.S.'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-6', 'Bolivia Oriental', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='SOMOS K'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-7', 'Quirigua', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='EXPRESS DEL FUTURO'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-8', 'Calle 80', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='SI 99 S.A.'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-9', 'Villas del Dorado', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='TRANSMASIVO'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '1-10', 'Bolivia - Bochica II', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Portal de la 80'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='TRANSMASIVO'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '5-2', 'Avenida Carrera 91', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Av. Cali'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='SI 99 S.A.'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '5-1', 'Suba Rincón', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Granja - Carrera 77'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='EXPRESS DEL FUTURO'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '5-3', 'Serena - Cerezos', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Granja - Carrera 77'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='SOMOS K'));
INSERT INTO RUTA_ALIMEN(ID_RUTA_ALIMEN, CODIGO, NOMBRE, ID_ESTACION, ID_OPERADOR) VALUES (SEQ_RUTALIM_ID.NEXTVAL, '5-4', 'Florida', (SELECT ID_ESTACION FROM ESTACION WHERE NOMBRE='Granja - Carrera 77'),(SELECT ID_OPERADOR FROM OPERADOR WHERE NOMBRE='GMOVIL S.A.S.'));

/*==============================================================*/
/* TIPO_PARADERO                                                */
/*==============================================================*/
INSERT INTO TIPO_PARADERO(ID_TIPO_PARADERO, NOMBRE, FIGURA) VALUES (SEQ_TIPA_ID.NEXTVAL, 'Mixta', 'Rombo');
INSERT INTO TIPO_PARADERO(ID_TIPO_PARADERO, NOMBRE, FIGURA) VALUES (SEQ_TIPA_ID.NEXTVAL, 'Desalimentación', 'Triangulo');
INSERT INTO TIPO_PARADERO(ID_TIPO_PARADERO, NOMBRE, FIGURA) VALUES (SEQ_TIPA_ID.NEXTVAL, 'Alimentación', 'Circulo');

/*==============================================================*/
/* PARADERO                                                     */
/*==============================================================*/
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 146A04', 'AC 80 - KR 107', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Triangulo'));
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 144A04', 'AC 80 - KR 109A', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Triangulo'));
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 135A04', 'DG 89A - KR 115', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Rombo'));
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 148A04', 'AC 80 - KR 107', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Triangulo'));
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 136A04', 'DG 89B - KR 115A', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Rombo'));
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 319A04', 'KR 117 - CL 89', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Rombo'));
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 11', 'KR 116A - CL 83', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Circulo'));
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 12', 'KR 116A - CL 81', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Circulo'));
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 13', 'KR 116B - CL 80A', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Circulo'));
INSERT INTO PARADERO(ID_PARADERO, NOMBRE, DIRECCION, LATITUD, LONGITUD, ID_TIPO_PARADERO) VALUES (SEQ_PAR_ID.NEXTVAL, 'Paradero 14', 'AC 80 - KR 110', NULL, NULL, (SELECT ID_TIPO_PARADERO FROM TIPO_PARADERO WHERE FIGURA='Circulo'));

/*==============================================================*/
/* PAR_RUT_ALIM                                                     */
/*==============================================================*/
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,1,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 146A04'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,2,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 144A04'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,3,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 135A04'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,4,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 148A04'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,5,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 136A04'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,6,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 319A04'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,7,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 14'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,8,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 12'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,9,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 13'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));
INSERT INTO PAR_RUT_ALIM (ID_PAR_RUT_ALIM, ORDEN, ID_PARADERO, ID_RUT_ALIM) VALUES (SEQ_PARRUTALIM_ID.NEXTVAL,10,(SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 11'),(SELECT ID_RUTA_ALIMEN FROM RUTA_ALIMEN WHERE CODIGO='1-4'));

/*==============================================================*/
/* PARA_HORA                                                    */
/*==============================================================*/
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 146A04'),(SELECT ID_HORARIO FROM HORARIO WHERE RANGO='E' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='09:00'));
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 146A04'), (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='D' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='08:00'));
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 146A04'), (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='S' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='11:00'));
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 135A04'), (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='E' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='05:00'));
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 135A04'), (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='S' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='10:00'));
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 11'), (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='E' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='04:00'));
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 12'), (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='S' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='06:00'));
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 13'), (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='D' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='03:00'));
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 14'), (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='D' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='07:00'));
INSERT INTO PARA_HORA(ID_PARA_HORA, ID_PARADERO, ID_HORARIO) VALUES (SEQ_PARHOR_ID.NEXTVAL, (SELECT ID_PARADERO FROM PARADERO WHERE NOMBRE='Paradero 319A04'), (SELECT ID_HORARIO FROM HORARIO WHERE RANGO='E' AND TO_CHAR(HORA_COMIENZO, 'HH24:MI')='04:30'));