/*==============================================================*/
/* PRIMARY KEY                                                  */
/*==============================================================*/
ALTER TABLE OPERADOR ADD CONSTRAINT OPE_PK_ID PRIMARY KEY (ID_OPERADOR);
ALTER TABLE TIPO_ESTACION ADD CONSTRAINT TIEST_PK_ID PRIMARY KEY (ID_TIPO_ESTA);
ALTER TABLE TRONCAL ADD CONSTRAINT TRON_PK_ID PRIMARY KEY (ID_TRONCAL);
ALTER TABLE ESTACION ADD CONSTRAINT EST_PK_ID PRIMARY KEY (ID_ESTACION);
ALTER TABLE VAGON ADD CONSTRAINT VAG_PK_ID PRIMARY KEY (ID_VAGON);
ALTER TABLE RUTA ADD CONSTRAINT RUT_PK_ID PRIMARY KEY (ID_RUTA);
ALTER TABLE RUTA_ESTA ADD CONSTRAINT RUTEST_PK_ID PRIMARY KEY (ID_RUTA_ESTA);
ALTER TABLE HORARIO ADD CONSTRAINT HOR_PK_ID PRIMARY KEY (ID_HORARIO);
ALTER TABLE RUTA_HORA ADD CONSTRAINT RUTHOR_PK_ID PRIMARY KEY (ID_RUTA_HORA);
ALTER TABLE RUTA_ALIMEN ADD CONSTRAINT RUTALIM_PK_ID PRIMARY KEY (ID_RUTA_ALIMEN);
ALTER TABLE TIPO_PARADERO ADD CONSTRAINT TIPAR_PK_ID PRIMARY KEY (ID_TIPO_PARADERO);
ALTER TABLE PARADERO ADD CONSTRAINT PAR_PK_ID PRIMARY KEY (ID_PARADERO);
ALTER TABLE PAR_RUT_ALIM ADD CONSTRAINT PARRUTLIM_PK_ID PRIMARY KEY (ID_PAR_RUT_ALIM);
ALTER TABLE PARA_HORA ADD CONSTRAINT PARHOR_PK_ID PRIMARY KEY (ID_PARA_HORA);


/*==============================================================*/
/* FOREIGN KEY                                                  */
/*==============================================================*/
ALTER TABLE TRONCAL ADD CONSTRAINT OPER_FK_TRON FOREIGN KEY (ID_OPERADOR) REFERENCES OPERADOR (ID_OPERADOR);

ALTER TABLE ESTACION ADD CONSTRAINT TRON_FK_EST FOREIGN KEY (ID_TRONCAL) REFERENCES TRONCAL(ID_TRONCAL);
ALTER TABLE ESTACION ADD CONSTRAINT TIEST_FK_EST FOREIGN KEY (ID_TIPO_ESTA) REFERENCES TIPO_ESTACION(ID_TIPO_ESTA);

ALTER TABLE VAGON ADD CONSTRAINT EST_FK_VAG FOREIGN KEY (ID_ESTACION) REFERENCES ESTACION (ID_ESTACION);

ALTER TABLE RUTA_ESTA ADD CONSTRAINT VAG_FK_RUTEST FOREIGN KEY (ID_VAGON) REFERENCES VAGON (ID_VAGON);
ALTER TABLE RUTA_ESTA ADD CONSTRAINT RUT_FK_RUTEST FOREIGN KEY (ID_RUTA) REFERENCES RUTA (ID_RUTA);

ALTER TABLE RUTA_HORA ADD CONSTRAINT HOR_FK_RUTHOR FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO (ID_HORARIO);
ALTER TABLE RUTA_HORA ADD CONSTRAINT RUT_FK_RUTHOR FOREIGN KEY (ID_RUTA) REFERENCES RUTA (ID_RUTA);

ALTER TABLE RUTA_ALIMEN ADD CONSTRAINT EST_FK_RUTALIM FOREIGN KEY (ID_ESTACION) REFERENCES ESTACION (ID_ESTACION);
ALTER TABLE RUTA_ALIMEN ADD CONSTRAINT RUTALIM_FK_TRON FOREIGN KEY (ID_OPERADOR) REFERENCES OPERADOR(ID_OPERADOR);

ALTER TABLE PARADERO ADD CONSTRAINT TIPAR_FK_PAR FOREIGN KEY (ID_TIPO_PARADERO) REFERENCES TIPO_PARADERO (ID_TIPO_PARADERO);

ALTER TABLE PAR_RUT_ALIM ADD CONSTRAINT TIPAR_FK_PAR FOREIGN KEY (ID_PARADERO) REFERENCES PARADERO (ID_PARADERO);
ALTER TABLE PAR_RUT_ALIM ADD CONSTRAINT TIPAR_FK_PAR FOREIGN KEY (ID_RUT_ALIM) REFERENCES RUTA_ALIMEN (ID_RUTA_ALIMEN);

ALTER TABLE PARA_HORA ADD CONSTRAINT PAR_FK_PARHOR FOREIGN KEY (ID_PARADERO) REFERENCES PARADERO (ID_PARADERO);
ALTER TABLE PARA_HORA ADD CONSTRAINT HOR_FK_PARHOR FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO (ID_HORARIO);


/*==============================================================*/
/* CHECK                                                        */
/*==============================================================*/
ALTER TABLE ESTACION ADD CONSTRAINT EST_CK_INCIAL CHECK (ESTA_INCIAL IN (0,1));
ALTER TABLE ESTACION ADD CONSTRAINT EST_CK_FINAL CHECK (ESTA_FINAL IN (0,1));

ALTER TABLE RUTA ADD CONSTRAINT RUT_CK_SENTIDO CHECK (SENTIDO IN ('N'/*Norte*/, 'S'/*Sur*/, 'O'/*Oeste*/, 'E'/*Este*/, 'NO'/*Noroeste*/, 'NE'/*Noreste*/, 'SO'/*Suroeste*/, 'SE'/*Sureste*/));

ALTER TABLE HORARIO ADD CONSTRAINT HOR_CK_RANGO CHECK (RANGO IN ('E'/*Entre semana*/, 'S'/*Sabado*/, 'D'/*Domingos o Festivos*/));
